# manifests/crew-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crew-service
  namespace: planet-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crew-service
  template:
    metadata:
      labels:
        app: crew-service
    spec:
      containers:
        - name: crew-service
          image: wilgrimthepilgrim/crew:latest
          env:
            - name: LOG_LEVEL
              value: "INFO"
          ports:
            - containerPort: 8080
            - containerPort: 2112
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: crew-service
  namespace: planet-express
  labels:
    app: crew-service
spec:
  selector:
    app: crew-service
  ports:
    - port: 80
      targetPort: 8080
    - port: 2112
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crew-service
  namespace: planet-express
spec:
  selector:
    matchLabels:
      app: crew-service
  endpoints:
    - port: metrics
