apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caddy
  namespace: argocd
spec:
  destination:
    namespace: caddy
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy
    repoURL: https://github.com/Gingercookie/caddy
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
