apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: fluent-bit
    helm:
      valueFiles:
      - $values/kube/logging/fluent-bit-values.yaml
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.48.9
  - ref: values
    repoURL: https://github.com/Gingercookie/homelab.git
    targetRevision: add-kube-manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
