// traffic/main.go
package main

import (
	"bytes"
	"encoding/json"
	"log/slog"
	"math/rand/v2"
	"net/http"
	"os"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

type DeliveryRequest struct {
	Recipient string `json:"recipient"`
	Address   string `json:"address"`
	Contents  string `json:"contents"`
}

var (
	apiURL = getEnv("API_URL", "http://planetexpress-api/deliveries")

	requestsGenerated = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "planet_express_traffic_requests_generated_total",
			Help: "The total number of requests generated by the traffic generator service",
		},
	)
)

func getEnv(key, def string) string {
	if val := os.Getenv(key); val != "" {
		return val
	}
	return def
}

var recipients = []string{
	"Philip J. Fry", "Turanga Leela", "Bender Bending Rodríguez",
	"Amy Wong", "Hermes Conrad", "Professor Farnsworth", "Zapp Brannigan", "Kif Kroker",
	"Mom", "Elzar", "Scruffy", "Robot Santa", "Calculon",
}

var addresses = []string{
	"New New York", "Mars Vegas", "Neptune", "Omicron Persei 8", "Robonia",
	"Luna Park", "Doop Headquarters", "Sewer City", "Central Bureaucracy",
}

var contents = []string{
	"Slurm", "Popplers", "Shiny metal parts", "Career chips", "Dark matter",
	"Mutant fish", "Love potion", "Explosives", "Robot oil", "Hyper-chicken eggs",
}

func randomChoice(list []string) string {
	return list[rand.IntN(len(list))]
}

func sendDelivery() {
	req := DeliveryRequest{
		Recipient: randomChoice(recipients),
		Address:   randomChoice(addresses),
		Contents:  randomChoice(contents),
	}

	data, _ := json.Marshal(req)
	requestsGenerated.Inc()

	resp, err := http.Post(apiURL, "application/json", bytes.NewBuffer(data))
	if err != nil {
		slog.Error("Failed to send delivery", "err", err)
		return
	}
	defer resp.Body.Close()

	slog.Info("Sent delivery", "recipient", req.Recipient, "address", req.Address, "contents", req.Contents, "status", resp.StatusCode)
}

func main() {
	levelStr := getEnv("LOG_LEVEL", "INFO")
	var level slog.Level
	if err := level.UnmarshalText([]byte(levelStr)); err != nil {
		level = slog.LevelInfo
	}
	slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: level})))

	interval := 1 * time.Second
	if val, ok := os.LookupEnv("INTERVAL_SECONDS"); ok {
		if val, err := time.ParseDuration(val + "s"); err == nil {
			interval = val
		}
	}

	prometheus.MustRegister(requestsGenerated)
	http.Handle("/metrics", promhttp.Handler())

	go func() {
		slog.Info("Prometheus metrics endpoint running", "addr", ":2112")
		err := http.ListenAndServe(":2112", nil)
		if err != nil {
			slog.Error("metrics server error", "err", err)
			os.Exit(1)
		}
	}()

	slog.Info("Delivery Traffic Generator running", "url", apiURL, "interval", interval)
	for {
		sendDelivery()
		time.Sleep(interval)
	}
}
