apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  version: 8.17.4
  count: 1
  elasticsearchRef:
    name: elastic
    namespace: logging
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
