apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps
  namespace: default
spec:
  tls:
    - hosts:
      - grafana.nogearnofalls.com
      secretName: wildcard-ngnf-tls
  ingressClassName: traefik
  rules:
    - host: grafana.nogearnofalls.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-grafana
                port:
                  number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps
  namespace: argocd
spec:
  tls:
    - hosts:
      - argocd.nogearnofalls.com
      secretName: wildcard-ngnf-tls
  ingressClassName: traefik
  rules:
    - host: argocd.nogearnofalls.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 4430

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps
  namespace: vault
spec:
  ingressClassName: traefik
  rules:
    - host: vault.nogearnofalls.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps
  namespace: logging
spec:
  ingressClassName: traefik
  tls:
    - hosts:
      - kibana.nogearnofalls.com
      secretName: wildcard-ngnf-tls
  rules:
    - host: kibana.nogearnofalls.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana-kb-http
                port:
                  number: 5601
